services:
  mysql:
    image: 'mysql:8'
    environment:
      MYSQL_DATABASE: leaderboard
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "33060:3306"

  app:
    build:
      context: .
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      QUEST_DARKORO_TOKEN:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/leaderboard
    #network_mode: host

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yaml
    depends_on:
      - app
    #network_mode: host
