schema:
  Guild:
    type: object
    properties:
      guild_id:
        required: true
        type: integer
        format: int64
      channel_id:
        required: true
        type: integer
        format: int64
      name:
        required: true
        type: string
      submission_channel_id:
        required: true
        type: integer
        format: int64
      permitted:
        required: true
        type: integer
        format: int64
  GuildsQueryResult:
    type: object
    properties:
      items:
        type: array
        required: true
        items:
          $ref: '#/schema/Guild'

  Board:
    type: object
    properties:
      id:
        readOnly: true
        type: string
        format: uuid
      level:
        required: true
        type: integer
      guild_id:
        required: true
        type: integer
        format: int64
      name:
        required: true
        type: string
      shared:
        required: true
        type: boolean
      pending:
        required: true
        type: boolean
  BoardsQueryResult:
    type: object
    properties:
      items:
        type: array
        required: true
        items:
          $ref: '#/schema/Board'
